title: Thomas Corrie
author: Thomas Corrie
description: Architect
email: thomas_corrie@hotmail.com
github_username: thomascorrie
theme: jekyll-theme-slate
url: https://thomascorrie.github.io/
baseurl: ""